name: fastAPI app

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=88 .
    - name: Lint with Mypy
      run: |
        mypy
    - name: Lint with Black
      run: |
        black --diff --check .
    - name: Lint with Isort
      run: |
        isort --check-only --diff --profile black .
